export const MESSAGE_CODES = {
  // Validation
  VALIDATION: {
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    INVALID_DATE_FORMAT: 'INVALID_DATE_FORMAT',
    EMAIL_REQUIRED: 'EMAIL_REQUIRED',
    EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
    PHONE_ALREADY_EXISTS: 'PHONE_ALREADY_EXISTS',
    NAME_ALREADY_EXISTS: 'NAME_ALREADY_EXISTS',
    ID_REQUIRED: 'ID_REQUIRED',
    IN_USE: 'IN_USE',
    INVALID_TYPE: 'INVALID_TYPE',
    INVALID_LANGUAGE: 'INVALID_LANGUAGE',
  },
  // Auth
  AUTH: {
    MISSING_CREDENTIALS: 'MISSING_CREDENTIALS',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    ACCOUNT_IS_LOCKED: 'ACCOUNT_IS_LOCKED',
    COMPANY_NOT_APPROVED: 'COMPANY_NOT_APPROVED',
    INVALID_OR_EXPIRED_TOKEN: 'INVALID_OR_EXPIRED_TOKEN',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    INVALID_TOKEN: 'INVALID_TOKEN',
    UNAUTHORIZED: 'UNAUTHORIZED',
    TOKEN_REQUIRED: 'TOKEN_REQUIRED',
    JWT_SECRET_NOT_SET: 'JWT_SECRET_NOT_SET',
    REFRESH_TOKEN_MISSING: 'REFRESH_TOKEN_MISSING',
    REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED',
    INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  },
  // Server
  SERVER: {
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  },
  // Success
  SUCCESS: {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    CREATED_SUCCESS: 'CREATED_SUCCESS',
    UPDATED_SUCCESS: 'UPDATED_SUCCESS',
    DELETED_SUCCESS: 'DELETED_SUCCESS',
    GET_ALL_SUCCESS: 'GET_ALL_SUCCESS',
    GET_SUCCESS: 'GET_SUCCESS',
    NOT_FOUND: 'NOT_FOUND',
    PASSWORD_RESET_EMAIL_SENT: 'PASSWORD_RESET_EMAIL_SENT',
    REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS',
  },
  FAIL: {
    EMAIL_SEND_FAILED: 'EMAIL_SEND_FAILED',
  },
};
